name: Build Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    strategy:
      # Let all builds finish even if one fails early
      fail-fast: false
      matrix:
        include:
          - build-target: f0_module
          - build-target: f1_rev2
          - build-target: f1_rev3
          - build-target: f1_dual
          - build-target: f1_dual_rev1

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.63.2
          cache: true

      - name: Install build tools
        run: |
          sudo apt-get install srecord libarchive-zip-perl

      - name: Build Firmware
        run: pixi run build ${{matrix.build-target}}

      - name: Attach binaries
        uses: actions/upload-artifact@v4
        with:
          name: Wideband ${{matrix.build-target}}
          path: ./firmware/deliver/${{matrix.build-target}}/wideband*

      - name: Zip artifacts
        run: zip Wideband\ ${{matrix.build-target}}.zip ./firmware/deliver/${{matrix.build-target}}/wideband*

      - name: Make a new Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Wideband\ ${{matrix.build-target}}.zip
